sudo: required

services:
  - docker

before_install:
  - docker build -t operable/cog-api-client-testing -f Dockerfile.ci .

# Need the job ID in order to upload the Coveralls data
script:
  - docker run -it --rm --env="TRAVIS_JOB_ID=${TRAVIS_JOB_ID}" operable/cog-api-client-testing mix coveralls.travis

notifications:
  slack:
    secure: U+Z/X10jpvUSCDhAbg72u8PPqjsiFdn6NAjvWVEoo/DbIyH+jat/sdZABb/66psS+SR66Kmxb3oRlPjN5q2j6eg2CRB/6oy6OJocl5XFhSw3maCVFOxvWfZA5BlTH3r7TNRgcCeIGiOlrebx9OYGCrieH6n+X6TcNNS0CyiMXS3I9zyfsmkgjiPp2eBGrbrlBiqnk1dnrth89WT+Srirb2/MId1zzRuQkyqZ4iGzr2CqxCh43m5J98JWY89dfC+AqbW59Q7TT9wJlq2bN4BM5F0tL5uCYbfmTDK1nMNsz/prfIK9DqglHfza3x5v0mAyVmg5vXnN4Bc4EeK5YO4bPAft6o2IFfnykt3r1/gbc3gs71O9FUlAs1Pg6cHtCFJUdLwSzC0B2TDbBx3gzdzMr+ZknLPr1dNWSmCw+BIvlp11JTnG4zwRBA5Fsbgmd0XsVamBZdxEsOcw+5Uxk//Q4fwdZfjMT8muHI8PCYfWmrp/B9phIpekIh4BtqR5NjkQ6kNIsE8b+QUNWrZ8qYviAlN6MZ6u9s3wIA8Jj1R2lsTmMuhTjiWABbXNo54UFd6n4Ifo1sz9b87D3t8KXWya53gS7S6V+kcXGr6UKcjyW3NVtQHnN2P8yGzNsFGxgvtsYvzY+Mt5tAJ+7PxEMsW3SMRQkg6q96hhkHJlcoorAeU=
